### ISSUE TITLE
TotalScanDistanceInMm appears zero

### ISSUE THREAD

**Issue by SusSysEngi** [Digital-Production-Aachen/OpenVectorFormatTools#36]
Hi, 
first of all, thank you for this great resource and work. I am currently working on a C# script to get the total scan distance per layer. However, I am struggling to understand my mistake or problem.  I used several .ovf files in case the one I have doesn't have laser tracks but still no success. I get zero. Given that I am new to C#, I wanted to ask here.

using OpenVectorFormat.FileReaderWriterFactory;
using OpenVectorFormat.AbstractReaderWriter;

// bunny (solidsupport).ovf
string filename = "bunny (solidsupport).ovf";
string fileExtension = ".ovf";

if (!FileReaderFactory.SupportedFileFormats.Contains(fileExtension))
{
    throw new Exception("Not supported");
}

// create progress object & file reader for this extension
IFileReaderWriterProgress progress = new FileReaderWriterProgress();
FileReader fileReader = FileReaderFactory.CreateNewReader(fileExtension);

// // read job
await fileReader.OpenJobAsync(filename, progress);

// // optional - cache the job completely to emory to have fast access
await fileReader.CacheJobToMemoryAsync();
    

OpenVectorFormat.Job jobshell = fileReader.JobShell;

double totalScanDistance = 0;
foreach (OpenVectorFormat.WorkPlane workPlane in jobshell.WorkPlanes)
{
    foreach (OpenVectorFormat.VectorBlock vectorBlock in workPlane.VectorBlocks)
    {
        double vectorBlockScanDistance = vectorBlock.MetaData.TotalScanDistanceInMm;
        totalScanDistance += vectorBlockScanDistance;
        Console.WriteLine("VectorBlock Scan Distance: " + vectorBlockScanDistance + " mm");
    }

    double workPlaneScanDistance = workPlane.MetaData.TotalScanDistanceInMm;
    totalScanDistance += workPlaneScanDistance;
    Console.WriteLine("Work Plane Scan Distance: " + workPlaneScanDistance + " mm");
}

Console.WriteLine("Total Scan Distance: " + totalScanDistance + " mm");

OpenVectorFormat.WorkPlane wp = await fileReader.GetWorkPlaneAsync(1);

double totalScanDistance_2 = wp.MetaData.TotalScanDistanceInMm;
Console.WriteLine("totalScanDistance2: " + totalScanDistance_2);

**Comment by SebastianDirks** [comment]
Hello @SusSysEngi,

thank your for your interest in our library.
Regarding your question:
The file reader only reads out the data that is in the file already. The ovf test files you opened don't have the meta data saved. We have 2 softwares that are unfortunatly not open source yet that write this meta data on export, our OVF slicer and our machine emulator. What software are your using to export OVF? Or are you converting another file type? All the formats we support for reading do not have the capability to store this meta data.
I currently only have an extension for computing the vector block bounds in this Repo. For most vector block types computing the lengths should be not too hard, but for elipses this gets compllicated. I will have a look if I can easily extract code to compute all vector block meta data from our softwware and add it here.

Best
Sebastian

**Comment by SebastianDirks** [comment]
@SusSysEngi I have just released version v1.6.2. You can update via Nuget. This release includes a method to calculate scan and jump distances and store them into the meta data. I also used it to store this data into the .ovf test files.

For usage you can best check out the [unit test](https://github.com/Digital-Production-Aachen/OpenVectorFormatTools/blob/0c2034a82aed87c1c0b3ee80f00e505ea50961b5/ReaderWriter/UnitTests/TestComputeMetaData.cs#L47). If you are interested in how to work with the vectors directly in C# using our library, have a look at the [implementation using System.Numerics.Vectors and our utils](https://github.com/Digital-Production-Aachen/OpenVectorFormatTools/blob/0c2034a82aed87c1c0b3ee80f00e505ea50961b5/ReaderWriter/OVFDefinition/VectorBlockExtensions.cs#L398).

Note that the mark distance is machine independant, however the jump distance is not. The meta data contains only the in vector block jump distance, but there are additional jumps caused by

1. Jumps between vector blocks, dependant on the exposure order the machine uses
2. Jumps added because of sky writing, dependant on the scanner controller parametrization
3. Jumps also change if the machine has multiple laser sources and performs scan field allocation. OVF can store this information in vector blocks using the laser index, but the algorithm implementation is always proprietary to the machine OEM (we use our own algorithms to approximate)

Let me know if you need further assistance.

**Comment by SusSysEngi** [comment]
@SebastianDirks Thank you so much for the support. I started using the new package with the new function. It helps a lot. I will check the VectorBlockExtensions.cs to work with vectors for a custom task.
